In [50]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [51]:
np.array([7, 8, 9])
np.zeros(5)
np.ones(5)

array([7, 8, 9])

array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1.])

In [52]:
matrix = [
    [1, 2, 3],
    [5, 6, 7]
]

print(matrix)
print(matrix[0])
print(matrix[0][0])

[[1, 2, 3], [5, 6, 7]]
[1, 2, 3]
1


In [53]:
for row in matrix:
  for elem in row:
    print(elem, end=",")

1,2,3,5,6,7,

In [54]:
for i in range(len(matrix)):
  for j in range(len(matrix[i])):
    print(f'{i}{j}', end=',')
  print()

00,01,02,
10,11,12,


In [55]:
matrix = np.array([
    [1, 2, 3],
    [5, 6, 7]
])

matrix
matrix[0]
matrix[0][0]
matrix[0, 0]  # convenience

array([[1, 2, 3],
       [5, 6, 7]])

array([1, 2, 3])

np.int64(1)

np.int64(1)

In [56]:
matrix.shape  # row, col
np.array([1, 2, 3]).shape

(2, 3)

(3,)

In [57]:
np.zeros(5)
np.zeros((3, 3))

array([0., 0., 0., 0., 0.])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
matrix = [
    [1, 2, 3],
    [5, 6, 7, 9]
]

matrix[1]
matrix[1][3]

[5, 6, 7, 9]

9

In [59]:
np.array([
    [1, 2, 3, 7],
    [5, 6, 7, 9]
]).shape

(2, 4)

In [60]:
arr = np.array([1, 2, 3])
arr.dtype, arr.itemsize  # 64 bits (8 bytes) integers

arr = np.array(['apple', 'banana'])  # longest str = banana = 6 chars
arr.dtype, arr.itemsize  # 6 chars of Unicode, encoded in UTF32 (32 bits = 4 bytes per char)

arr = np.array(['pineapple', 'banana'])  # longest str = pineapple = 9 chars
arr.dtype, arr.itemsize  # 9 chars of Unicode

arr = np.array([1, 'pineapple'])
arr.dtype, arr.itemsize  # 21 chars of Unicode (extra spaces for conversions)

(dtype('int64'), 8)

(dtype('<U6'), 24)

(dtype('<U9'), 36)

(dtype('<U21'), 84)

In [61]:
np.eye(2)  # identity matrix, 1s on diagonals, 0s everywhere else
np.eye(3)

array([[1., 0.],
       [0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
arr = np.array([1, 2, 3])
arr.ndim, arr.shape, arr.size

arr = np.array([[45, 50], [55, 60]])
arr.ndim, arr.shape, arr.size

arr = np.array([
    [[45, 50], [55, 60]],
    [[12, 50], [55, 67]],
])
arr.ndim, arr.shape, arr.size

(1, (3,), 3)

(2, (2, 2), 4)

(3, (2, 2, 2), 8)

In [63]:
# get sample from std. normal distribution (mean = 0, std.dev = 1)
np.random.randn()
np.random.randn(5)
np.random.randn(2, 3)

-0.17242820755043575

array([-0.8779,  0.0422,  0.5828, -1.1006,  1.1447])

array([[ 0.9016,  0.5025,  0.9009],
       [-0.6837, -0.1229, -0.9358]])

In [64]:
np.random.randint(5)  # low
np.random.randint(5, 10)  # low, high
np.random.randint(5, 10, 5)  # low, high, size
np.random.randint(5, 10, (2, 3))

1

8

array([9, 8, 6, 8, 5], dtype=int32)

array([[5, 7, 7],
       [6, 8, 9]], dtype=int32)

In [65]:
# evenly spaced integers
np.linspace(1, 5, 5)
np.linspace(1, 5, 10)

array([1., 2., 3., 4., 5.])

array([1.    , 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111,
       4.5556, 5.    ])

In [66]:
# continuous integers
np.arange(10)
np.arange(10, 20)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
arr = np.zeros(16)
arr.shape
arr.reshape(4, 4).shape
arr.reshape(8, 2).shape
arr.reshape(2, 8).shape
arr.reshape(2, 2, 4).shape
arr.reshape(2, 2, 2, 2).shape

(16,)

(4, 4)

(8, 2)

(2, 8)

(2, 2, 4)

(2, 2, 2, 2)

In [68]:
arr = np.zeros((8, 4))
arr.size
arr.reshape(16, 2).shape
arr.reshape(8, 2, 2).shape
arr.reshape(4, 4, 2).shape

32

(16, 2)

(8, 2, 2)

(4, 4, 2)

In [69]:
arr = np.array([7, 8, 9])
arr
arr.shape
np.expand_dims(arr, 1)
np.expand_dims(arr, 1).shape

array([7, 8, 9])

(3,)

array([[7],
       [8],
       [9]])

(3, 1)

In [70]:
arr = np.array([[1], [2], [3]])
arr
arr.shape
np.squeeze(arr)
np.squeeze(arr).shape

array([[1],
       [2],
       [3]])

(3, 1)

array([1, 2, 3])

(3,)

In [71]:
matrix = np.array([
    [10, 11, 12],
    [15, 16, 17],
])

matrix.T  # transpose

array([[10, 15],
       [11, 16],
       [12, 17]])

In [72]:
np.hstack((
    np.array([5, 6, 7]),
    np.array([4, 5, 9]),
))

np.vstack((
    np.array([5, 6, 7]),
    np.array([4, 5, 9]),
))

array([5, 6, 7, 4, 5, 9])

array([[5, 6, 7],
       [4, 5, 9]])

In [73]:
np.stack((
    np.array([5, 6, 7]),
    np.array([4, 5, 9]),
), axis=0)

np.stack((
    np.array([5, 6, 7]),
    np.array([4, 5, 9]),
), axis=1)

array([[5, 6, 7],
       [4, 5, 9]])

array([[5, 4],
       [6, 5],
       [7, 9]])

In [74]:
np.concatenate((
    np.array([5, 6, 7]),
    np.array([4, 5, 9]),
), axis=0)

array([5, 6, 7, 4, 5, 9])

In [75]:
np.concatenate((
    np.array([[5, 6], [7, 8]]),
    np.array([[1, 2], [3, 4]]),
), axis=0)

np.concatenate((
    np.array([[5, 6], [7, 8]]),
    np.array([[1, 2], [3, 4]]),
), axis=1)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [76]:
np.arange(10).sum()
np.arange(10).mean()
np.arange(10).var()
np.arange(10).std()
np.arange(10).min()
np.arange(10).max()

np.int64(45)

np.float64(4.5)

np.float64(8.25)

np.float64(2.8722813232690143)

np.int64(0)

np.int64(9)

In [77]:
matrix = np.array([
    [9, 10, 11, 12],
    [1, 2, 1, 2],
    [50, 0, 1, 100]
])

matrix.sum()
matrix.sum(axis=0)
matrix.sum(axis=1)

np.int64(199)

array([ 60,  12,  13, 114])

array([ 42,   6, 151])

Broadcasting

Same operation is done for every element

In [78]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 7])

arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2
arr1 // arr2

array([ 6,  8, 10])

array([-4, -4, -4])

array([ 5, 12, 21])

array([0.2   , 0.3333, 0.4286])

array([0, 0, 0])

In [79]:
np.array([1, 2, 3]) + 10
np.array([1, 2, 3]) * 10
np.array([1, 2, 3]) % 2

array([11, 12, 13])

array([10, 20, 30])

array([1, 0, 1])

In [80]:
arr = np.array([
    [4, 5, 6],
    [10, 11, 12]
])

arr + 10
arr + np.array([1, 2, 3])

array([[14, 15, 16],
       [20, 21, 22]])

array([[ 5,  7,  9],
       [11, 13, 15]])

In [81]:
arr = np.array([10, 15, 7, 9, 20])
(arr % 5 == 0).sum()

np.int64(3)

In [82]:
arr = np.array([10, 26, 1, 71, 8])
arr[0]  # get i=0 elem
arr[[0, 1]]  # get i=0, i=1 elem (fancy indexing)
arr[[False, False, False, True, True]]  # bool mask

np.int64(10)

array([10, 26])

array([71,  8])

In [83]:
arr = np.array([10, 15, 7, 9, 20])
arr[arr % 5 == 0]  # extract elems using bool mask
arr[(arr % 5 == 0) & (arr >= 15)]  # combine conditions

array([10, 15, 20])

array([15, 20])

In [84]:
arr = np.array([10, 15, 7, 9, 20])
np.where(arr >= 10)  # indices where cond. is True
np.where(arr >= 10, 'apple', 'banana')
np.where(arr >= 10, 1, 0)

(array([0, 1, 4]),)

array(['apple', 'apple', 'banana', 'banana', 'apple'], dtype='<U6')

array([1, 1, 0, 0, 1])

In [85]:
arr = np.array([10, 15, 7, 9, 20])
arr.max()
arr.argmax()

np.int64(20)

np.int64(4)

### Challenge 1: The Normalizer

In [86]:
np.random.seed(1)

data = np.random.randint(0, 100, (10, 4))  # 10 samples, 4 features
_min = data.min(axis=0)
_max = data.max(axis=0)

data_scaled = (data - _min) / (_max - _min)
data_scaled

array([[0.4186, 0.1379, 0.7412, 0.0225],
       [0.8605, 0.0575, 0.8235, 0.6404],
       [0.1744, 0.0115, 0.7882, 0.7191],
       [0.0581, 0.2874, 0.4824, 0.1461],
       [0.1977, 0.9655, 0.0235, 0.236 ],
       [0.3256, 0.1609, 0.4824, 0.6854],
       [1.    , 1.    , 1.    , 1.    ],
       [0.9884, 0.1494, 0.    , 0.    ],
       [0.7209, 0.7011, 0.1529, 0.5618],
       [0.    , 0.    , 0.6   , 0.8315]])

In [242]:
data_scaled.min(axis=0)
data_scaled.max(axis=0)

array([0., 0., 0., 0.])

array([1., 1., 1., 1.])

In [87]:
data = np.array([
    # salary, age, pocket_money
    [10000, 20, 560],
    [13400, 44, 120],
    [9400, 12, 1200],
    [5000, 52, 1900],
])

_min = data.min(axis=0)
_max = data.max(axis=0)

(data - _min) / (_max - _min)

array([[0.5952, 0.2   , 0.2472],
       [1.    , 0.8   , 0.    ],
       [0.5238, 0.    , 0.6067],
       [0.    , 1.    , 1.    ]])

### Challenge 2: The "Borders" Logic

In [88]:
data = np.zeros((10, 10))

In [89]:
data[:, 0] = 1  # all rows, col=0
data[:, -1] = 1  # all rows, col=-1
data[0, :] = 1  # row=0, all cols
data[-1, :] = 1  # row=-1, all cols
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [90]:
data[1:-1:2, 1:-1:2] = 5
data[2:-1:2, 2:-1:2] = 5
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [91]:
data[4:6, 4:6] = 9
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 9., 9., 5., 0., 5., 1.],
       [1., 5., 0., 5., 9., 9., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 5., 0., 5., 0., 5., 0., 5., 0., 1.],
       [1., 0., 5., 0., 5., 0., 5., 0., 5., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [92]:
data = np.array([
    [15, 17, 22, 45],
    [31, 32, 33, 34],
    [56, 58, 12, 19],
    [2, 3, 4, 5],
])

In [93]:
# slicing syntax
# data[start:stop:step, start:stop:step]
data[0]
data[0, 0]
data[:, :-1]

array([15, 17, 22, 45])

np.int64(15)

array([[15, 17, 22],
       [31, 32, 33],
       [56, 58, 12],
       [ 2,  3,  4]])

### Challenge 3: The Outlier Finder

In [135]:
data = np.random.randn(100)

In [136]:
mask = np.abs(data - data.mean()) > (2 * data.std())
mask

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [137]:
mean_before = data.mean()
mean_before

data[mask] = 99.9
mask.sum()  # Count how many values were replaced

mean_after = data.mean()
mean_after

np.float64(0.0602440368007225)

np.int64(4)

np.float64(4.098532191921347)

In [211]:
data = np.array([5, 10, 30, 40, 50, 60, 1, -10])
mask = np.abs(data - data.mean()) > data.std()  # elem too far away from mean
data[mask] = 1000
mask.sum()  # these many you replaced

np.int64(3)

### Challenge 4: Image-Style Manipulations (Channel Swapping)

In [139]:
data = np.random.randint(0, 256, (10, 10, 3))

In [144]:
# "Mute" the Green channel by setting all its values to 0.
data[:, :, 1] = 0

In [ ]:
# Check if any pixel has a Red value greater than 200 and a Blue value less than 50.
mask = (data[:, :, 0] > 200) & (data[:, :, 2] < 50)
mask.sum()

np.int64(5)

In [152]:
# average "brightness" of the image
data.mean()

np.float64(90.62333333333333)

### Challenge 5: The "Close Neighbors" Search

In [231]:
points = np.random.random((10, 2))
origin = (0, 0)

In [240]:
np.sqrt(points[:, 0]**2 + points[:, 1]**2)

np.linalg.norm(points, axis=1)

array([1.1471, 0.8611, 0.7657, 0.5183, 0.6024, 0.7698, 0.9711, 1.1356,
       0.2867, 1.1959])

array([1.1471, 0.8611, 0.7657, 0.5183, 0.6024, 0.7698, 0.9711, 1.1356,
       0.2867, 1.1959])

In [241]:
np.argmin(np.linalg.norm(points, axis=1))

np.int64(8)